language: php
dist: trusty
sudo: required
php:
  - '5.4'
  - '7.1'
install:
  - composer update
  - composer dump-autoload
  - cp .env.example .env
script: composer test-all
cache:
  apt: true
  directories:
    - $TRAVIS_BUILD_DIR/vendor
    - $HOME/.composer/cache
